# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, and test .NET Core application.
name: NtpService

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: NtpService                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: NtpUnitTests\NtpUnitTests.csproj                  # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build the application
    - name: Buid the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:PostBuildEvent=""
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --collect:"XPlat Code Coverage"
    
      # Install ReportGenerator
    - name: Install ReportGenerator CLI
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.4.8
    
    # Generate and present coverage report`
    - name: Coverage Report
      run: |
        reportgenerator -reports:NtpUnitTests/TestResults/**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html;TextSummary
        type coveragereport\Summary.txt
